replicaCount: 1

image:
  repository: 630013977255.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-prod/evaluation-service
  tag: "648a77b"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8003

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 8003
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: 8003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

serviceAccount:
  create: true
  name: evaluation-service

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

keda:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  pollingInterval: 30
  cooldownPeriod: 300
  queueLength: 5

namespace: evaluation-service
