replicaCount: 0

image:
  repository: 630013977255.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-prod/targeting-service
  tag: "b30409b-fix1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8004

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 8004
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: 8004
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

namespace: targeting-service
