# ConfigMap do evaluation-service
# Contém variáveis NÃO sensíveis
# As credenciais AWS vêm automaticamente via IRSA (ServiceAccount annotation)
apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: evaluation-service
  labels:
    app: evaluation-service
    version: "1.0"
data:
  PORT: "8004"
  AWS_REGION: "us-east-1"
  # DNS interno dos serviços dependentes
  FLAG_SERVICE_URL: "http://flag-service.flag-service.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service.targeting-service.svc.cluster.local:8003"
  # URL da fila SQS — obter com: terraform output -json connection_strings | jq '.sqs_queue_url'
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/630013977255/tech-challenge-prod-evaluation-events"
