replicaCount: 1

image:
  repository: 630013977255.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-prod/auth-service
  tag: "07e2294"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8001

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  httpGet:
    path: /health
    port: 8001
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /health
    port: 8001
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

namespace: auth-service
